package com.seidor.inventario.model;
// Generated 22 may. 2023 18:00:34 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Almacen generated by hbm2java
 */
public class Almacen implements java.io.Serializable {

	private Integer idAlmacen;
	private String almacen;
	private String descripcion;
	private int activo;
	private Set empleados = new HashSet(0);
	private Set entradas = new HashSet(0);
	private Set productos = new HashSet(0);

	public Almacen() {
	}

	public Almacen(String almacen, int activo) {
		this.almacen = almacen;
		this.activo = activo;
	}

	public Almacen(String almacen, String descripcion, int activo, Set empleados, Set entradas, Set productos) {
		this.almacen = almacen;
		this.descripcion = descripcion;
		this.activo = activo;
		this.empleados = empleados;
		this.entradas = entradas;
		this.productos = productos;
	}

	public Integer getIdAlmacen() {
		return this.idAlmacen;
	}

	public void setIdAlmacen(Integer idAlmacen) {
		this.idAlmacen = idAlmacen;
	}

	public String getAlmacen() {
		return this.almacen;
	}

	public void setAlmacen(String almacen) {
		this.almacen = almacen;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public int getActivo() {
		return this.activo;
	}

	public void setActivo(int activo) {
		this.activo = activo;
	}

	public Set getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set empleados) {
		this.empleados = empleados;
	}

	public Set getEntradas() {
		return this.entradas;
	}

	public void setEntradas(Set entradas) {
		this.entradas = entradas;
	}

	public Set getProductos() {
		return this.productos;
	}

	public void setProductos(Set productos) {
		this.productos = productos;
	}

}
