package com.seidor.inventario.model;
// Generated 3 mar. 2023 11:27:00 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria implements java.io.Serializable {

	private Integer idCategoria;
	private String categoria;
	private String descripcion;
	private int activo;
	private Set productos = new HashSet(0);

	public Categoria() {
	}

	public Categoria(String categoria, int activo) {
		this.categoria = categoria;
		this.activo = activo;
	}

	public Categoria(String categoria, String descripcion, int activo, Set productos) {
		this.categoria = categoria;
		this.descripcion = descripcion;
		this.activo = activo;
		this.productos = productos;
	}

	public Integer getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(Integer idCategoria) {
		this.idCategoria = idCategoria;
	}

	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public int getActivo() {
		return this.activo;
	}

	public void setActivo(int activo) {
		this.activo = activo;
	}

	public Set getProductos() {
		return this.productos;
	}

	public void setProductos(Set productos) {
		this.productos = productos;
	}

}
