package com.seidor.inventario.model;
// Generated 22 may. 2023 18:00:34 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private Integer idCliente;
	private String nombre;
	private String rfc;
	private String direccion;
	private String telefono;
	private String extension;
	private String EMail;
	private int activo;
	private Set ordenCompras = new HashSet(0);

	public Cliente() {
	}

	public Cliente(int activo) {
		this.activo = activo;
	}

	public Cliente(String nombre, String rfc, String direccion, String telefono, String extension, String EMail,
			int activo, Set ordenCompras) {
		this.nombre = nombre;
		this.rfc = rfc;
		this.direccion = direccion;
		this.telefono = telefono;
		this.extension = extension;
		this.EMail = EMail;
		this.activo = activo;
		this.ordenCompras = ordenCompras;
	}

	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	public String getEMail() {
		return this.EMail;
	}

	public void setEMail(String EMail) {
		this.EMail = EMail;
	}

	public int getActivo() {
		return this.activo;
	}

	public void setActivo(int activo) {
		this.activo = activo;
	}

	public Set getOrdenCompras() {
		return this.ordenCompras;
	}

	public void setOrdenCompras(Set ordenCompras) {
		this.ordenCompras = ordenCompras;
	}

}
