package com.seidor.inventario.model;
// Generated 4 mar. 2024 12:06:49 by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * DatosBancarios generated by hbm2java
 */
public class DatosBancarios implements java.io.Serializable {

	private Integer idDatosBancarios;
	private Proveedor proveedor;
	private String banco;
	private String cta;
	private String clabe;
	private Integer estatus;
	private boolean fdl;
	private int cbu;
	private Date cat;
	private int luu;
	private Date uat;

	public DatosBancarios() {
	}

	public DatosBancarios(boolean fdl, int cbu, Date cat, int luu, Date uat) {
		this.fdl = fdl;
		this.cbu = cbu;
		this.cat = cat;
		this.luu = luu;
		this.uat = uat;
	}

	public DatosBancarios(Proveedor proveedor, String banco, String cta, String clabe, Integer estatus, boolean fdl,
			int cbu, Date cat, int luu, Date uat) {
		this.proveedor = proveedor;
		this.banco = banco;
		this.cta = cta;
		this.clabe = clabe;
		this.estatus = estatus;
		this.fdl = fdl;
		this.cbu = cbu;
		this.cat = cat;
		this.luu = luu;
		this.uat = uat;
	}

	public Integer getIdDatosBancarios() {
		return this.idDatosBancarios;
	}

	public void setIdDatosBancarios(Integer idDatosBancarios) {
		this.idDatosBancarios = idDatosBancarios;
	}

	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	public String getBanco() {
		return this.banco;
	}

	public void setBanco(String banco) {
		this.banco = banco;
	}

	public String getCta() {
		return this.cta;
	}

	public void setCta(String cta) {
		this.cta = cta;
	}

	public String getClabe() {
		return this.clabe;
	}

	public void setClabe(String clabe) {
		this.clabe = clabe;
	}

	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	public boolean isFdl() {
		return this.fdl;
	}

	public void setFdl(boolean fdl) {
		this.fdl = fdl;
	}

	public int getCbu() {
		return this.cbu;
	}

	public void setCbu(int cbu) {
		this.cbu = cbu;
	}

	public Date getCat() {
		return this.cat;
	}

	public void setCat(Date cat) {
		this.cat = cat;
	}

	public int getLuu() {
		return this.luu;
	}

	public void setLuu(int luu) {
		this.luu = luu;
	}

	public Date getUat() {
		return this.uat;
	}

	public void setUat(Date uat) {
		this.uat = uat;
	}

}
