package com.seidor.inventario.model;
// Generated 4 mar. 2024 12:06:49 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DetalleOrdenCompra generated by hbm2java
 */
public class DetalleOrdenCompra implements java.io.Serializable {

	private Integer idDetalleOc;
	private Almacen almacen;
	private OrdenCompra ordenCompra;
	private Producto producto;
	private TipoMoneda tipoMoneda;
	private Date fecha;
	private double cantidad;
	private BigDecimal precioUnitario;
	private BigDecimal precioUnitarioMxn;
	private double cantidadFactura;
	private int estatus;
	private boolean fdl;
	private int cbu;
	private Date cat;
	private int luu;
	private Date uat;
	private Set detalleMovimientos = new HashSet(0);

	public DetalleOrdenCompra() {
	}

	public DetalleOrdenCompra(Almacen almacen, OrdenCompra ordenCompra, Producto producto, Date fecha, double cantidad,
			double cantidadFactura, int estatus, boolean fdl, int cbu, Date cat, int luu, Date uat) {
		this.almacen = almacen;
		this.ordenCompra = ordenCompra;
		this.producto = producto;
		this.fecha = fecha;
		this.cantidad = cantidad;
		this.cantidadFactura = cantidadFactura;
		this.estatus = estatus;
		this.fdl = fdl;
		this.cbu = cbu;
		this.cat = cat;
		this.luu = luu;
		this.uat = uat;
	}

	public DetalleOrdenCompra(Almacen almacen, OrdenCompra ordenCompra, Producto producto, TipoMoneda tipoMoneda,
			Date fecha, double cantidad, BigDecimal precioUnitario, BigDecimal precioUnitarioMxn,
			double cantidadFactura, int estatus, boolean fdl, int cbu, Date cat, int luu, Date uat,
			Set detalleMovimientos) {
		this.almacen = almacen;
		this.ordenCompra = ordenCompra;
		this.producto = producto;
		this.tipoMoneda = tipoMoneda;
		this.fecha = fecha;
		this.cantidad = cantidad;
		this.precioUnitario = precioUnitario;
		this.precioUnitarioMxn = precioUnitarioMxn;
		this.cantidadFactura = cantidadFactura;
		this.estatus = estatus;
		this.fdl = fdl;
		this.cbu = cbu;
		this.cat = cat;
		this.luu = luu;
		this.uat = uat;
		this.detalleMovimientos = detalleMovimientos;
	}

	public Integer getIdDetalleOc() {
		return this.idDetalleOc;
	}

	public void setIdDetalleOc(Integer idDetalleOc) {
		this.idDetalleOc = idDetalleOc;
	}

	public Almacen getAlmacen() {
		return this.almacen;
	}

	public void setAlmacen(Almacen almacen) {
		this.almacen = almacen;
	}

	public OrdenCompra getOrdenCompra() {
		return this.ordenCompra;
	}

	public void setOrdenCompra(OrdenCompra ordenCompra) {
		this.ordenCompra = ordenCompra;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public TipoMoneda getTipoMoneda() {
		return this.tipoMoneda;
	}

	public void setTipoMoneda(TipoMoneda tipoMoneda) {
		this.tipoMoneda = tipoMoneda;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public double getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(double cantidad) {
		this.cantidad = cantidad;
	}

	public BigDecimal getPrecioUnitario() {
		return this.precioUnitario;
	}

	public void setPrecioUnitario(BigDecimal precioUnitario) {
		this.precioUnitario = precioUnitario;
	}

	public BigDecimal getPrecioUnitarioMxn() {
		return this.precioUnitarioMxn;
	}

	public void setPrecioUnitarioMxn(BigDecimal precioUnitarioMxn) {
		this.precioUnitarioMxn = precioUnitarioMxn;
	}

	public double getCantidadFactura() {
		return this.cantidadFactura;
	}

	public void setCantidadFactura(double cantidadFactura) {
		this.cantidadFactura = cantidadFactura;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public boolean isFdl() {
		return this.fdl;
	}

	public void setFdl(boolean fdl) {
		this.fdl = fdl;
	}

	public int getCbu() {
		return this.cbu;
	}

	public void setCbu(int cbu) {
		this.cbu = cbu;
	}

	public Date getCat() {
		return this.cat;
	}

	public void setCat(Date cat) {
		this.cat = cat;
	}

	public int getLuu() {
		return this.luu;
	}

	public void setLuu(int luu) {
		this.luu = luu;
	}

	public Date getUat() {
		return this.uat;
	}

	public void setUat(Date uat) {
		this.uat = uat;
	}

	public Set getDetalleMovimientos() {
		return this.detalleMovimientos;
	}

	public void setDetalleMovimientos(Set detalleMovimientos) {
		this.detalleMovimientos = detalleMovimientos;
	}

}
