package com.seidor.inventario.model;
// Generated 22 feb. 2023 19:54:18 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Entrada generated by hbm2java
 */
public class Entrada implements java.io.Serializable {

	private Integer idEntrada;
	private Almacen almacen;
	private Empleado empleado;
	private Factura factura;
	private OrdenCompra ordenCompra;
	private Producto producto;
	private Proyecto proyecto;
	private Ubicacion ubicacion;
	private UnidadMedida unidadMedida;
	private Date fecha;
	private Integer cantidad;
	private BigDecimal precioUnitario;
	private Integer estatus;

	public Entrada() {
	}

	public Entrada(Producto producto) {
		this.producto = producto;
	}

	public Entrada(Almacen almacen, Empleado empleado, Factura factura, OrdenCompra ordenCompra, Producto producto,
			Proyecto proyecto, Ubicacion ubicacion, UnidadMedida unidadMedida, Date fecha, Integer cantidad,
			BigDecimal precioUnitario, Integer estatus) {
		this.almacen = almacen;
		this.empleado = empleado;
		this.factura = factura;
		this.ordenCompra = ordenCompra;
		this.producto = producto;
		this.proyecto = proyecto;
		this.ubicacion = ubicacion;
		this.unidadMedida = unidadMedida;
		this.fecha = fecha;
		this.cantidad = cantidad;
		this.precioUnitario = precioUnitario;
		this.estatus = estatus;
	}

	public Integer getIdEntrada() {
		return this.idEntrada;
	}

	public void setIdEntrada(Integer idEntrada) {
		this.idEntrada = idEntrada;
	}

	public Almacen getAlmacen() {
		return this.almacen;
	}

	public void setAlmacen(Almacen almacen) {
		this.almacen = almacen;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public Factura getFactura() {
		return this.factura;
	}

	public void setFactura(Factura factura) {
		this.factura = factura;
	}

	public OrdenCompra getOrdenCompra() {
		return this.ordenCompra;
	}

	public void setOrdenCompra(OrdenCompra ordenCompra) {
		this.ordenCompra = ordenCompra;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

	public Ubicacion getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(Ubicacion ubicacion) {
		this.ubicacion = ubicacion;
	}

	public UnidadMedida getUnidadMedida() {
		return this.unidadMedida;
	}

	public void setUnidadMedida(UnidadMedida unidadMedida) {
		this.unidadMedida = unidadMedida;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	public BigDecimal getPrecioUnitario() {
		return this.precioUnitario;
	}

	public void setPrecioUnitario(BigDecimal precioUnitario) {
		this.precioUnitario = precioUnitario;
	}

	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

}
