package com.seidor.inventario.model;
// Generated 12 abr. 2024 12:10:56 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EstatusProyecto generated by hbm2java
 */
public class EstatusProyecto implements java.io.Serializable {

	private Integer idEstatusProyecto;
	private String descripcion;
	private boolean fdl;
	private int cbu;
	private Date cat;
	private int luu;
	private Date uat;
	private Set proyectos = new HashSet(0);

	public EstatusProyecto() {
	}

	public EstatusProyecto(String descripcion, boolean fdl, int cbu, Date cat, int luu, Date uat) {
		this.descripcion = descripcion;
		this.fdl = fdl;
		this.cbu = cbu;
		this.cat = cat;
		this.luu = luu;
		this.uat = uat;
	}

	public EstatusProyecto(String descripcion, boolean fdl, int cbu, Date cat, int luu, Date uat, Set proyectos) {
		this.descripcion = descripcion;
		this.fdl = fdl;
		this.cbu = cbu;
		this.cat = cat;
		this.luu = luu;
		this.uat = uat;
		this.proyectos = proyectos;
	}

	public Integer getIdEstatusProyecto() {
		return this.idEstatusProyecto;
	}

	public void setIdEstatusProyecto(Integer idEstatusProyecto) {
		this.idEstatusProyecto = idEstatusProyecto;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public boolean isFdl() {
		return this.fdl;
	}

	public void setFdl(boolean fdl) {
		this.fdl = fdl;
	}

	public int getCbu() {
		return this.cbu;
	}

	public void setCbu(int cbu) {
		this.cbu = cbu;
	}

	public Date getCat() {
		return this.cat;
	}

	public void setCat(Date cat) {
		this.cat = cat;
	}

	public int getLuu() {
		return this.luu;
	}

	public void setLuu(int luu) {
		this.luu = luu;
	}

	public Date getUat() {
		return this.uat;
	}

	public void setUat(Date uat) {
		this.uat = uat;
	}

	public Set getProyectos() {
		return this.proyectos;
	}

	public void setProyectos(Set proyectos) {
		this.proyectos = proyectos;
	}

}
