package com.seidor.inventario.model;
// Generated 22 may. 2023 18:00:34 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * EstatusOrdenCompra generated by hbm2java
 */
public class EstatusOrdenCompra implements java.io.Serializable {

	private Integer idEstatusOrdenCompra;
	private String estatusOrdenCompra;
	private String descripcion;
	private Integer activo;
	private Set ordenCompras = new HashSet(0);

	public EstatusOrdenCompra() {
	}

	public EstatusOrdenCompra(String estatusOrdenCompra, String descripcion, Integer activo, Set ordenCompras) {
		this.estatusOrdenCompra = estatusOrdenCompra;
		this.descripcion = descripcion;
		this.activo = activo;
		this.ordenCompras = ordenCompras;
	}

	public Integer getIdEstatusOrdenCompra() {
		return this.idEstatusOrdenCompra;
	}

	public void setIdEstatusOrdenCompra(Integer idEstatusOrdenCompra) {
		this.idEstatusOrdenCompra = idEstatusOrdenCompra;
	}

	public String getEstatusOrdenCompra() {
		return this.estatusOrdenCompra;
	}

	public void setEstatusOrdenCompra(String estatusOrdenCompra) {
		this.estatusOrdenCompra = estatusOrdenCompra;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getActivo() {
		return this.activo;
	}

	public void setActivo(Integer activo) {
		this.activo = activo;
	}

	public Set getOrdenCompras() {
		return this.ordenCompras;
	}

	public void setOrdenCompras(Set ordenCompras) {
		this.ordenCompras = ordenCompras;
	}

}
