package com.seidor.inventario.model;
// Generated 25 ene. 2023 18:48:44 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Etapa generated by hbm2java
 */
public class Etapa implements java.io.Serializable {

	private Integer idEtapa;
	private String etapa;
	private String descripcion;
	private int activo;
	private Set ordenCompras = new HashSet(0);

	public Etapa() {
	}

	public Etapa(String etapa, int activo) {
		this.etapa = etapa;
		this.activo = activo;
	}

	public Etapa(String etapa, String descripcion, int activo, Set ordenCompras) {
		this.etapa = etapa;
		this.descripcion = descripcion;
		this.activo = activo;
		this.ordenCompras = ordenCompras;
	}

	public Integer getIdEtapa() {
		return this.idEtapa;
	}

	public void setIdEtapa(Integer idEtapa) {
		this.idEtapa = idEtapa;
	}

	public String getEtapa() {
		return this.etapa;
	}

	public void setEtapa(String etapa) {
		this.etapa = etapa;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public int getActivo() {
		return this.activo;
	}

	public void setActivo(int activo) {
		this.activo = activo;
	}

	public Set getOrdenCompras() {
		return this.ordenCompras;
	}

	public void setOrdenCompras(Set ordenCompras) {
		this.ordenCompras = ordenCompras;
	}

}
