package com.seidor.inventario.model;
// Generated 21 jun. 2024 15:15:13 by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * Folios generated by hbm2java
 */
public class Folios implements java.io.Serializable {

	private Integer idFolio;
	private TiposMovimiento tiposMovimiento;
	private int consecutivo;
	private String abrev;
	private Boolean fdl;
	private Integer cbu;
	private Date cat;
	private Integer luu;
	private Date uat;

	public Folios() {
	}

	public Folios(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public Folios(TiposMovimiento tiposMovimiento, int consecutivo, String abrev, Boolean fdl, Integer cbu, Date cat,
			Integer luu, Date uat) {
		this.tiposMovimiento = tiposMovimiento;
		this.consecutivo = consecutivo;
		this.abrev = abrev;
		this.fdl = fdl;
		this.cbu = cbu;
		this.cat = cat;
		this.luu = luu;
		this.uat = uat;
	}

	public Integer getIdFolio() {
		return this.idFolio;
	}

	public void setIdFolio(Integer idFolio) {
		this.idFolio = idFolio;
	}

	public TiposMovimiento getTiposMovimiento() {
		return this.tiposMovimiento;
	}

	public void setTiposMovimiento(TiposMovimiento tiposMovimiento) {
		this.tiposMovimiento = tiposMovimiento;
	}

	public int getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public String getAbrev() {
		return this.abrev;
	}

	public void setAbrev(String abrev) {
		this.abrev = abrev;
	}

	public Boolean getFdl() {
		return this.fdl;
	}

	public void setFdl(Boolean fdl) {
		this.fdl = fdl;
	}

	public Integer getCbu() {
		return this.cbu;
	}

	public void setCbu(Integer cbu) {
		this.cbu = cbu;
	}

	public Date getCat() {
		return this.cat;
	}

	public void setCat(Date cat) {
		this.cat = cat;
	}

	public Integer getLuu() {
		return this.luu;
	}

	public void setLuu(Integer luu) {
		this.luu = luu;
	}

	public Date getUat() {
		return this.uat;
	}

	public void setUat(Date uat) {
		this.uat = uat;
	}

}
