package com.seidor.inventario.model;
// Generated 4 mar. 2024 12:06:49 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Movimientos generated by hbm2java
 */
public class Movimientos implements java.io.Serializable {

	private Integer idMovimiento;
	private Almacen almacen;
	private Area area;
	private Empleado empleado;
	private Factura factura;
	private OrdenCompra ordenCompra;
	private Proyecto proyecto;
	private TiposMovimiento tiposMovimiento;
	private String folio;
	private Date fecha;
	private Integer estatus;
	private String ordenTrabajo;
	private String cveMueble;
	private Boolean fdl;
	private Integer cbu;
	private Date cat;
	private Integer luu;
	private Date uat;
	private Set detalleMovimientos = new HashSet(0);
	private Set entradas = new HashSet(0);
	private Set salidas = new HashSet(0);

	public Movimientos() {
	}

	public Movimientos(Almacen almacen, Area area, Empleado empleado, Factura factura, OrdenCompra ordenCompra,
			Proyecto proyecto, TiposMovimiento tiposMovimiento, String folio, Date fecha, Integer estatus,
			String ordenTrabajo, String cveMueble, Boolean fdl, Integer cbu, Date cat, Integer luu, Date uat,
			Set detalleMovimientos, Set entradas, Set salidas) {
		this.almacen = almacen;
		this.area = area;
		this.empleado = empleado;
		this.factura = factura;
		this.ordenCompra = ordenCompra;
		this.proyecto = proyecto;
		this.tiposMovimiento = tiposMovimiento;
		this.folio = folio;
		this.fecha = fecha;
		this.estatus = estatus;
		this.ordenTrabajo = ordenTrabajo;
		this.cveMueble = cveMueble;
		this.fdl = fdl;
		this.cbu = cbu;
		this.cat = cat;
		this.luu = luu;
		this.uat = uat;
		this.detalleMovimientos = detalleMovimientos;
		this.entradas = entradas;
		this.salidas = salidas;
	}

	public Integer getIdMovimiento() {
		return this.idMovimiento;
	}

	public void setIdMovimiento(Integer idMovimiento) {
		this.idMovimiento = idMovimiento;
	}

	public Almacen getAlmacen() {
		return this.almacen;
	}

	public void setAlmacen(Almacen almacen) {
		this.almacen = almacen;
	}

	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public Factura getFactura() {
		return this.factura;
	}

	public void setFactura(Factura factura) {
		this.factura = factura;
	}

	public OrdenCompra getOrdenCompra() {
		return this.ordenCompra;
	}

	public void setOrdenCompra(OrdenCompra ordenCompra) {
		this.ordenCompra = ordenCompra;
	}

	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

	public TiposMovimiento getTiposMovimiento() {
		return this.tiposMovimiento;
	}

	public void setTiposMovimiento(TiposMovimiento tiposMovimiento) {
		this.tiposMovimiento = tiposMovimiento;
	}

	public String getFolio() {
		return this.folio;
	}

	public void setFolio(String folio) {
		this.folio = folio;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	public String getOrdenTrabajo() {
		return this.ordenTrabajo;
	}

	public void setOrdenTrabajo(String ordenTrabajo) {
		this.ordenTrabajo = ordenTrabajo;
	}

	public String getCveMueble() {
		return this.cveMueble;
	}

	public void setCveMueble(String cveMueble) {
		this.cveMueble = cveMueble;
	}

	public Boolean getFdl() {
		return this.fdl;
	}

	public void setFdl(Boolean fdl) {
		this.fdl = fdl;
	}

	public Integer getCbu() {
		return this.cbu;
	}

	public void setCbu(Integer cbu) {
		this.cbu = cbu;
	}

	public Date getCat() {
		return this.cat;
	}

	public void setCat(Date cat) {
		this.cat = cat;
	}

	public Integer getLuu() {
		return this.luu;
	}

	public void setLuu(Integer luu) {
		this.luu = luu;
	}

	public Date getUat() {
		return this.uat;
	}

	public void setUat(Date uat) {
		this.uat = uat;
	}

	public Set getDetalleMovimientos() {
		return this.detalleMovimientos;
	}

	public void setDetalleMovimientos(Set detalleMovimientos) {
		this.detalleMovimientos = detalleMovimientos;
	}

	public Set getEntradas() {
		return this.entradas;
	}

	public void setEntradas(Set entradas) {
		this.entradas = entradas;
	}

	public Set getSalidas() {
		return this.salidas;
	}

	public void setSalidas(Set salidas) {
		this.salidas = salidas;
	}

}
