package com.seidor.inventario.model;
// Generated 21 dic. 2023 9:34:58 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Movimientos generated by hbm2java
 */
public class Movimientos implements java.io.Serializable {

	private Integer idMovimiento;
	private Almacen almacen;
	private Factura factura;
	private OrdenCompra ordenCompra;
	private TiposMovimiento tiposMovimiento;
	private String folio;
	private Date fecha;
	private Integer estatus;
	private Boolean fdl;
	private Integer cbu;
	private Date cat;
	private Integer luu;
	private Date uat;
	private Set detalleMovimientos = new HashSet(0);

	public Movimientos() {
	}

	public Movimientos(Almacen almacen, Factura factura, OrdenCompra ordenCompra, TiposMovimiento tiposMovimiento,
			String folio, Date fecha, Integer estatus, Boolean fdl, Integer cbu, Date cat, Integer luu, Date uat,
			Set detalleMovimientos) {
		this.almacen = almacen;
		this.factura = factura;
		this.ordenCompra = ordenCompra;
		this.tiposMovimiento = tiposMovimiento;
		this.folio = folio;
		this.fecha = fecha;
		this.estatus = estatus;
		this.fdl = fdl;
		this.cbu = cbu;
		this.cat = cat;
		this.luu = luu;
		this.uat = uat;
		this.detalleMovimientos = detalleMovimientos;
	}

	public Integer getIdMovimiento() {
		return this.idMovimiento;
	}

	public void setIdMovimiento(Integer idMovimiento) {
		this.idMovimiento = idMovimiento;
	}

	public Almacen getAlmacen() {
		return this.almacen;
	}

	public void setAlmacen(Almacen almacen) {
		this.almacen = almacen;
	}

	public Factura getFactura() {
		return this.factura;
	}

	public void setFactura(Factura factura) {
		this.factura = factura;
	}

	public OrdenCompra getOrdenCompra() {
		return this.ordenCompra;
	}

	public void setOrdenCompra(OrdenCompra ordenCompra) {
		this.ordenCompra = ordenCompra;
	}

	public TiposMovimiento getTiposMovimiento() {
		return this.tiposMovimiento;
	}

	public void setTiposMovimiento(TiposMovimiento tiposMovimiento) {
		this.tiposMovimiento = tiposMovimiento;
	}

	public String getFolio() {
		return this.folio;
	}

	public void setFolio(String folio) {
		this.folio = folio;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	public Boolean getFdl() {
		return this.fdl;
	}

	public void setFdl(Boolean fdl) {
		this.fdl = fdl;
	}

	public Integer getCbu() {
		return this.cbu;
	}

	public void setCbu(Integer cbu) {
		this.cbu = cbu;
	}

	public Date getCat() {
		return this.cat;
	}

	public void setCat(Date cat) {
		this.cat = cat;
	}

	public Integer getLuu() {
		return this.luu;
	}

	public void setLuu(Integer luu) {
		this.luu = luu;
	}

	public Date getUat() {
		return this.uat;
	}

	public void setUat(Date uat) {
		this.uat = uat;
	}

	public Set getDetalleMovimientos() {
		return this.detalleMovimientos;
	}

	public void setDetalleMovimientos(Set detalleMovimientos) {
		this.detalleMovimientos = detalleMovimientos;
	}

}
