package com.seidor.inventario.model;
// Generated 22 feb. 2023 19:54:18 by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * MovimientosStock generated by hbm2java
 */
public class MovimientosStock implements java.io.Serializable {

	private Integer idMovimientoStock;
	private Producto producto;
	private Proyecto proyecto;
	private Date fecha;
	private Integer tipo;
	private Integer cantidad;
	private Integer estatus;

	public MovimientosStock() {
	}

	public MovimientosStock(Producto producto, Proyecto proyecto, Date fecha, Integer tipo, Integer cantidad,
			Integer estatus) {
		this.producto = producto;
		this.proyecto = proyecto;
		this.fecha = fecha;
		this.tipo = tipo;
		this.cantidad = cantidad;
		this.estatus = estatus;
	}

	public Integer getIdMovimientoStock() {
		return this.idMovimientoStock;
	}

	public void setIdMovimientoStock(Integer idMovimientoStock) {
		this.idMovimientoStock = idMovimientoStock;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Integer getTipo() {
		return this.tipo;
	}

	public void setTipo(Integer tipo) {
		this.tipo = tipo;
	}

	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

}
