package com.seidor.inventario.model;
// Generated 4 mar. 2024 12:06:49 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrdenCompra generated by hbm2java
 */
public class OrdenCompra implements java.io.Serializable {

	private Integer idOrdenCompra;
	private Almacen almacen;
	private Area area;
	private Cliente cliente;
	private Empleado empleado;
	private EstatusOrdenCompra estatusOrdenCompra;
	private Etapa etapa;
	private Proveedor proveedor;
	private Proyecto proyecto;
	private TipoMoneda tipoMoneda;
	private TipoOrdenCompra tipoOrdenCompra;
	private String descripcion;
	private Date fecha;
	private Date fechaRecepAlmacen;
	private String noPresupuesto;
	private String noRequisicion;
	private String lugarEntrega;
	private String tiempoEntrega;
	private Date fechaCambio;
	private BigDecimal tipoCambio;
	private boolean isIva;
	private boolean isIsr;
	private boolean fdl;
	private int cbu;
	private Date cat;
	private int luu;
	private Date uat;
	private Set facturas = new HashSet(0);
	private Set movimientoses = new HashSet(0);
	private Set entradas = new HashSet(0);
	private Set detalleOrdenCompras = new HashSet(0);

	public OrdenCompra() {
	}

	public OrdenCompra(Area area, Cliente cliente, Empleado empleado, Etapa etapa, TipoOrdenCompra tipoOrdenCompra,
			boolean isIva, boolean isIsr, boolean fdl, int cbu, Date cat, int luu, Date uat) {
		this.area = area;
		this.cliente = cliente;
		this.empleado = empleado;
		this.etapa = etapa;
		this.tipoOrdenCompra = tipoOrdenCompra;
		this.isIva = isIva;
		this.isIsr = isIsr;
		this.fdl = fdl;
		this.cbu = cbu;
		this.cat = cat;
		this.luu = luu;
		this.uat = uat;
	}

	public OrdenCompra(Almacen almacen, Area area, Cliente cliente, Empleado empleado,
			EstatusOrdenCompra estatusOrdenCompra, Etapa etapa, Proveedor proveedor, Proyecto proyecto,
			TipoMoneda tipoMoneda, TipoOrdenCompra tipoOrdenCompra, String descripcion, Date fecha,
			Date fechaRecepAlmacen, String noPresupuesto, String noRequisicion, String lugarEntrega,
			String tiempoEntrega, Date fechaCambio, BigDecimal tipoCambio, boolean isIva, boolean isIsr, boolean fdl,
			int cbu, Date cat, int luu, Date uat, Set facturas, Set movimientoses, Set entradas,
			Set detalleOrdenCompras) {
		this.almacen = almacen;
		this.area = area;
		this.cliente = cliente;
		this.empleado = empleado;
		this.estatusOrdenCompra = estatusOrdenCompra;
		this.etapa = etapa;
		this.proveedor = proveedor;
		this.proyecto = proyecto;
		this.tipoMoneda = tipoMoneda;
		this.tipoOrdenCompra = tipoOrdenCompra;
		this.descripcion = descripcion;
		this.fecha = fecha;
		this.fechaRecepAlmacen = fechaRecepAlmacen;
		this.noPresupuesto = noPresupuesto;
		this.noRequisicion = noRequisicion;
		this.lugarEntrega = lugarEntrega;
		this.tiempoEntrega = tiempoEntrega;
		this.fechaCambio = fechaCambio;
		this.tipoCambio = tipoCambio;
		this.isIva = isIva;
		this.isIsr = isIsr;
		this.fdl = fdl;
		this.cbu = cbu;
		this.cat = cat;
		this.luu = luu;
		this.uat = uat;
		this.facturas = facturas;
		this.movimientoses = movimientoses;
		this.entradas = entradas;
		this.detalleOrdenCompras = detalleOrdenCompras;
	}

	public Integer getIdOrdenCompra() {
		return this.idOrdenCompra;
	}

	public void setIdOrdenCompra(Integer idOrdenCompra) {
		this.idOrdenCompra = idOrdenCompra;
	}

	public Almacen getAlmacen() {
		return this.almacen;
	}

	public void setAlmacen(Almacen almacen) {
		this.almacen = almacen;
	}

	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public EstatusOrdenCompra getEstatusOrdenCompra() {
		return this.estatusOrdenCompra;
	}

	public void setEstatusOrdenCompra(EstatusOrdenCompra estatusOrdenCompra) {
		this.estatusOrdenCompra = estatusOrdenCompra;
	}

	public Etapa getEtapa() {
		return this.etapa;
	}

	public void setEtapa(Etapa etapa) {
		this.etapa = etapa;
	}

	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

	public TipoMoneda getTipoMoneda() {
		return this.tipoMoneda;
	}

	public void setTipoMoneda(TipoMoneda tipoMoneda) {
		this.tipoMoneda = tipoMoneda;
	}

	public TipoOrdenCompra getTipoOrdenCompra() {
		return this.tipoOrdenCompra;
	}

	public void setTipoOrdenCompra(TipoOrdenCompra tipoOrdenCompra) {
		this.tipoOrdenCompra = tipoOrdenCompra;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getFechaRecepAlmacen() {
		return this.fechaRecepAlmacen;
	}

	public void setFechaRecepAlmacen(Date fechaRecepAlmacen) {
		this.fechaRecepAlmacen = fechaRecepAlmacen;
	}

	public String getNoPresupuesto() {
		return this.noPresupuesto;
	}

	public void setNoPresupuesto(String noPresupuesto) {
		this.noPresupuesto = noPresupuesto;
	}

	public String getNoRequisicion() {
		return this.noRequisicion;
	}

	public void setNoRequisicion(String noRequisicion) {
		this.noRequisicion = noRequisicion;
	}

	public String getLugarEntrega() {
		return this.lugarEntrega;
	}

	public void setLugarEntrega(String lugarEntrega) {
		this.lugarEntrega = lugarEntrega;
	}

	public String getTiempoEntrega() {
		return this.tiempoEntrega;
	}

	public void setTiempoEntrega(String tiempoEntrega) {
		this.tiempoEntrega = tiempoEntrega;
	}

	public Date getFechaCambio() {
		return this.fechaCambio;
	}

	public void setFechaCambio(Date fechaCambio) {
		this.fechaCambio = fechaCambio;
	}

	public BigDecimal getTipoCambio() {
		return this.tipoCambio;
	}

	public void setTipoCambio(BigDecimal tipoCambio) {
		this.tipoCambio = tipoCambio;
	}

	public boolean isIsIva() {
		return this.isIva;
	}

	public void setIsIva(boolean isIva) {
		this.isIva = isIva;
	}

	public boolean isIsIsr() {
		return this.isIsr;
	}

	public void setIsIsr(boolean isIsr) {
		this.isIsr = isIsr;
	}

	public boolean isFdl() {
		return this.fdl;
	}

	public void setFdl(boolean fdl) {
		this.fdl = fdl;
	}

	public int getCbu() {
		return this.cbu;
	}

	public void setCbu(int cbu) {
		this.cbu = cbu;
	}

	public Date getCat() {
		return this.cat;
	}

	public void setCat(Date cat) {
		this.cat = cat;
	}

	public int getLuu() {
		return this.luu;
	}

	public void setLuu(int luu) {
		this.luu = luu;
	}

	public Date getUat() {
		return this.uat;
	}

	public void setUat(Date uat) {
		this.uat = uat;
	}

	public Set getFacturas() {
		return this.facturas;
	}

	public void setFacturas(Set facturas) {
		this.facturas = facturas;
	}

	public Set getMovimientoses() {
		return this.movimientoses;
	}

	public void setMovimientoses(Set movimientoses) {
		this.movimientoses = movimientoses;
	}

	public Set getEntradas() {
		return this.entradas;
	}

	public void setEntradas(Set entradas) {
		this.entradas = entradas;
	}

	public Set getDetalleOrdenCompras() {
		return this.detalleOrdenCompras;
	}

	public void setDetalleOrdenCompras(Set detalleOrdenCompras) {
		this.detalleOrdenCompras = detalleOrdenCompras;
	}

}
