package com.seidor.inventario.model;
// Generated 3 mar. 2023 11:27:00 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil implements java.io.Serializable {

	private Integer idPerfil;
	private String nombre;
	private String descripcion;
	private int activo;
	private Set perfilUsuarios = new HashSet(0);

	public Perfil() {
	}

	public Perfil(String nombre, String descripcion, int activo) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.activo = activo;
	}

	public Perfil(String nombre, String descripcion, int activo, Set perfilUsuarios) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.activo = activo;
		this.perfilUsuarios = perfilUsuarios;
	}

	public Integer getIdPerfil() {
		return this.idPerfil;
	}

	public void setIdPerfil(Integer idPerfil) {
		this.idPerfil = idPerfil;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public int getActivo() {
		return this.activo;
	}

	public void setActivo(int activo) {
		this.activo = activo;
	}

	public Set getPerfilUsuarios() {
		return this.perfilUsuarios;
	}

	public void setPerfilUsuarios(Set perfilUsuarios) {
		this.perfilUsuarios = perfilUsuarios;
	}

}
