package com.seidor.inventario.model;
// Generated 29 mar. 2023 21:04:16 by Hibernate Tools 4.3.5.Final

import org.springframework.context.annotation.Profile;

/**
 * PerfilUsuario generated by hbm2java
 */
public class PerfilUsuario implements java.io.Serializable {

	private Integer idPerfilUsuario;
	private Perfil perfil;
	private Usuario usuario;
	private int activo;

	public PerfilUsuario() {
	}

	public PerfilUsuario(Perfil perfil, Usuario usuario, int activo) {
		this.perfil = perfil;
		this.usuario = usuario;
		this.activo = activo;
	}

	public Integer getIdPerfilUsuario() {
		return this.idPerfilUsuario;
	}

	public void setIdPerfilUsuario(Integer idPerfilUsuario) {
		this.idPerfilUsuario = idPerfilUsuario;
	}

	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public int getActivo() {
		return this.activo;
	}

	public void setActivo(int activo) {
		this.activo = activo;
	}

	public void setFdl(boolean b) {
		// TODO Auto-generated method stub
		
	}

}
