package com.seidor.inventario.model;
// Generated 21 dic. 2023 9:34:58 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	private Integer idProducto;
	private Almacen almacen;
	private Categoria categoria;
	private UnidadMedida unidadMedida;
	private String codigo;
	private String nombre;
	private Double cantidad;
	private BigDecimal precioCompra;
	private BigDecimal precioVenta;
	private String urlImagen;
	private Integer minimo;
	private Integer maximo;
	private Date fecha;
	private String observaciones;
	private Double stock;
	private boolean fdl;
	private int cbu;
	private Date cat;
	private int luu;
	private Date uat;
	private Set detalleOrdenCompras = new HashSet(0);
	private Set movimientosStocks = new HashSet(0);
	private Set entradas = new HashSet(0);
	private Set detalleMovimientos = new HashSet(0);
	private Set salidas = new HashSet(0);

	public Producto() {
	}

	public Producto(Almacen almacen, Categoria categoria, UnidadMedida unidadMedida, String codigo, String nombre,
			boolean fdl, int cbu, Date cat, int luu, Date uat) {
		this.almacen = almacen;
		this.categoria = categoria;
		this.unidadMedida = unidadMedida;
		this.codigo = codigo;
		this.nombre = nombre;
		this.fdl = fdl;
		this.cbu = cbu;
		this.cat = cat;
		this.luu = luu;
		this.uat = uat;
	}

	public Producto(Almacen almacen, Categoria categoria, UnidadMedida unidadMedida, String codigo, String nombre,
			Double cantidad, BigDecimal precioCompra, BigDecimal precioVenta, String urlImagen, Integer minimo,
			Integer maximo, Date fecha, String observaciones, Double stock, boolean fdl, int cbu, Date cat, int luu,
			Date uat, Set detalleOrdenCompras, Set movimientosStocks, Set entradas, Set detalleMovimientos,
			Set salidas) {
		this.almacen = almacen;
		this.categoria = categoria;
		this.unidadMedida = unidadMedida;
		this.codigo = codigo;
		this.nombre = nombre;
		this.cantidad = cantidad;
		this.precioCompra = precioCompra;
		this.precioVenta = precioVenta;
		this.urlImagen = urlImagen;
		this.minimo = minimo;
		this.maximo = maximo;
		this.fecha = fecha;
		this.observaciones = observaciones;
		this.stock = stock;
		this.fdl = fdl;
		this.cbu = cbu;
		this.cat = cat;
		this.luu = luu;
		this.uat = uat;
		this.detalleOrdenCompras = detalleOrdenCompras;
		this.movimientosStocks = movimientosStocks;
		this.entradas = entradas;
		this.detalleMovimientos = detalleMovimientos;
		this.salidas = salidas;
	}

	public Integer getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Integer idProducto) {
		this.idProducto = idProducto;
	}

	public Almacen getAlmacen() {
		return this.almacen;
	}

	public void setAlmacen(Almacen almacen) {
		this.almacen = almacen;
	}

	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public UnidadMedida getUnidadMedida() {
		return this.unidadMedida;
	}

	public void setUnidadMedida(UnidadMedida unidadMedida) {
		this.unidadMedida = unidadMedida;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Double getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Double cantidad) {
		this.cantidad = cantidad;
	}

	public BigDecimal getPrecioCompra() {
		return this.precioCompra;
	}

	public void setPrecioCompra(BigDecimal precioCompra) {
		this.precioCompra = precioCompra;
	}

	public BigDecimal getPrecioVenta() {
		return this.precioVenta;
	}

	public void setPrecioVenta(BigDecimal precioVenta) {
		this.precioVenta = precioVenta;
	}

	public String getUrlImagen() {
		return this.urlImagen;
	}

	public void setUrlImagen(String urlImagen) {
		this.urlImagen = urlImagen;
	}

	public Integer getMinimo() {
		return this.minimo;
	}

	public void setMinimo(Integer minimo) {
		this.minimo = minimo;
	}

	public Integer getMaximo() {
		return this.maximo;
	}

	public void setMaximo(Integer maximo) {
		this.maximo = maximo;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Double getStock() {
		return this.stock;
	}

	public void setStock(Double stock) {
		this.stock = stock;
	}

	public boolean isFdl() {
		return this.fdl;
	}

	public void setFdl(boolean fdl) {
		this.fdl = fdl;
	}

	public int getCbu() {
		return this.cbu;
	}

	public void setCbu(int cbu) {
		this.cbu = cbu;
	}

	public Date getCat() {
		return this.cat;
	}

	public void setCat(Date cat) {
		this.cat = cat;
	}

	public int getLuu() {
		return this.luu;
	}

	public void setLuu(int luu) {
		this.luu = luu;
	}

	public Date getUat() {
		return this.uat;
	}

	public void setUat(Date uat) {
		this.uat = uat;
	}

	public Set getDetalleOrdenCompras() {
		return this.detalleOrdenCompras;
	}

	public void setDetalleOrdenCompras(Set detalleOrdenCompras) {
		this.detalleOrdenCompras = detalleOrdenCompras;
	}

	public Set getMovimientosStocks() {
		return this.movimientosStocks;
	}

	public void setMovimientosStocks(Set movimientosStocks) {
		this.movimientosStocks = movimientosStocks;
	}

	public Set getEntradas() {
		return this.entradas;
	}

	public void setEntradas(Set entradas) {
		this.entradas = entradas;
	}

	public Set getDetalleMovimientos() {
		return this.detalleMovimientos;
	}

	public void setDetalleMovimientos(Set detalleMovimientos) {
		this.detalleMovimientos = detalleMovimientos;
	}

	public Set getSalidas() {
		return this.salidas;
	}

	public void setSalidas(Set salidas) {
		this.salidas = salidas;
	}

}
