package com.seidor.inventario.model;
// Generated 22 feb. 2023 19:54:18 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor implements java.io.Serializable {

	private Integer idProveedor;
	private String nombre;
	private String rfc;
	private String direccion;
	private String telefono;
	private String extension;
	private String EMail;
	private int activo;
	private Set facturas = new HashSet(0);

	public Proveedor() {
	}

	public Proveedor(String nombre, int activo) {
		this.nombre = nombre;
		this.activo = activo;
	}

	public Proveedor(String nombre, String rfc, String direccion, String telefono, String extension, String EMail,
			int activo, Set facturas) {
		this.nombre = nombre;
		this.rfc = rfc;
		this.direccion = direccion;
		this.telefono = telefono;
		this.extension = extension;
		this.EMail = EMail;
		this.activo = activo;
		this.facturas = facturas;
	}

	public Integer getIdProveedor() {
		return this.idProveedor;
	}

	public void setIdProveedor(Integer idProveedor) {
		this.idProveedor = idProveedor;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	public String getEMail() {
		return this.EMail;
	}

	public void setEMail(String EMail) {
		this.EMail = EMail;
	}

	public int getActivo() {
		return this.activo;
	}

	public void setActivo(int activo) {
		this.activo = activo;
	}

	public Set getFacturas() {
		return this.facturas;
	}

	public void setFacturas(Set facturas) {
		this.facturas = facturas;
	}

}
