package com.seidor.inventario.model;
// Generated 21 dic. 2023 9:34:58 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto implements java.io.Serializable {

	private Integer idProyecto;
	private Empleado empleado;
	private EstatusProyecto estatusProyecto;
	private String nombre;
	private Date fechaInicio;
	private Date fechaFinal;
	private String numeroPresupuesto;
	private boolean fdl;
	private int cbu;
	private Date cat;
	private int luu;
	private Date uat;
	private Set salidas = new HashSet(0);
	private Set entradas = new HashSet(0);
	private Set movimientosStocks = new HashSet(0);
	private Set ordenCompras = new HashSet(0);

	public Proyecto() {
	}

	public Proyecto(EstatusProyecto estatusProyecto, String nombre, boolean fdl, int cbu, Date cat, int luu, Date uat) {
		this.estatusProyecto = estatusProyecto;
		this.nombre = nombre;
		this.fdl = fdl;
		this.cbu = cbu;
		this.cat = cat;
		this.luu = luu;
		this.uat = uat;
	}

	public Proyecto(Empleado empleado, EstatusProyecto estatusProyecto, String nombre, Date fechaInicio,
			Date fechaFinal, String numeroPresupuesto, boolean fdl, int cbu, Date cat, int luu, Date uat, Set salidas,
			Set entradas, Set movimientosStocks, Set ordenCompras) {
		this.empleado = empleado;
		this.estatusProyecto = estatusProyecto;
		this.nombre = nombre;
		this.fechaInicio = fechaInicio;
		this.fechaFinal = fechaFinal;
		this.numeroPresupuesto = numeroPresupuesto;
		this.fdl = fdl;
		this.cbu = cbu;
		this.cat = cat;
		this.luu = luu;
		this.uat = uat;
		this.salidas = salidas;
		this.entradas = entradas;
		this.movimientosStocks = movimientosStocks;
		this.ordenCompras = ordenCompras;
	}

	public Integer getIdProyecto() {
		return this.idProyecto;
	}

	public void setIdProyecto(Integer idProyecto) {
		this.idProyecto = idProyecto;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public EstatusProyecto getEstatusProyecto() {
		return this.estatusProyecto;
	}

	public void setEstatusProyecto(EstatusProyecto estatusProyecto) {
		this.estatusProyecto = estatusProyecto;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFinal() {
		return this.fechaFinal;
	}

	public void setFechaFinal(Date fechaFinal) {
		this.fechaFinal = fechaFinal;
	}

	public String getNumeroPresupuesto() {
		return this.numeroPresupuesto;
	}

	public void setNumeroPresupuesto(String numeroPresupuesto) {
		this.numeroPresupuesto = numeroPresupuesto;
	}

	public boolean isFdl() {
		return this.fdl;
	}

	public void setFdl(boolean fdl) {
		this.fdl = fdl;
	}

	public int getCbu() {
		return this.cbu;
	}

	public void setCbu(int cbu) {
		this.cbu = cbu;
	}

	public Date getCat() {
		return this.cat;
	}

	public void setCat(Date cat) {
		this.cat = cat;
	}

	public int getLuu() {
		return this.luu;
	}

	public void setLuu(int luu) {
		this.luu = luu;
	}

	public Date getUat() {
		return this.uat;
	}

	public void setUat(Date uat) {
		this.uat = uat;
	}

	public Set getSalidas() {
		return this.salidas;
	}

	public void setSalidas(Set salidas) {
		this.salidas = salidas;
	}

	public Set getEntradas() {
		return this.entradas;
	}

	public void setEntradas(Set entradas) {
		this.entradas = entradas;
	}

	public Set getMovimientosStocks() {
		return this.movimientosStocks;
	}

	public void setMovimientosStocks(Set movimientosStocks) {
		this.movimientosStocks = movimientosStocks;
	}

	public Set getOrdenCompras() {
		return this.ordenCompras;
	}

	public void setOrdenCompras(Set ordenCompras) {
		this.ordenCompras = ordenCompras;
	}

}
