package com.seidor.inventario.model;
// Generated 21 jun. 2024 15:15:13 by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * RegimenFiscal generated by hbm2java
 */
public class RegimenFiscal implements java.io.Serializable {

	private Integer idRegimenFiscal;
	private String regimenFiscal;
	private String descripcion;
	private Boolean fdl;
	private Integer cbu;
	private Date cat;
	private Integer luu;
	private Date uat;

	public RegimenFiscal() {
	}

	public RegimenFiscal(String regimenFiscal, String descripcion, Boolean fdl, Integer cbu, Date cat, Integer luu,
			Date uat) {
		this.regimenFiscal = regimenFiscal;
		this.descripcion = descripcion;
		this.fdl = fdl;
		this.cbu = cbu;
		this.cat = cat;
		this.luu = luu;
		this.uat = uat;
	}

	public Integer getIdRegimenFiscal() {
		return this.idRegimenFiscal;
	}

	public void setIdRegimenFiscal(Integer idRegimenFiscal) {
		this.idRegimenFiscal = idRegimenFiscal;
	}

	public String getRegimenFiscal() {
		return this.regimenFiscal;
	}

	public void setRegimenFiscal(String regimenFiscal) {
		this.regimenFiscal = regimenFiscal;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Boolean getFdl() {
		return this.fdl;
	}

	public void setFdl(Boolean fdl) {
		this.fdl = fdl;
	}

	public Integer getCbu() {
		return this.cbu;
	}

	public void setCbu(Integer cbu) {
		this.cbu = cbu;
	}

	public Date getCat() {
		return this.cat;
	}

	public void setCat(Date cat) {
		this.cat = cat;
	}

	public Integer getLuu() {
		return this.luu;
	}

	public void setLuu(Integer luu) {
		this.luu = luu;
	}

	public Date getUat() {
		return this.uat;
	}

	public void setUat(Date uat) {
		this.uat = uat;
	}

}
