package com.seidor.inventario.model;
// Generated 29 mar. 2023 21:04:16 by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * Salida generated by hbm2java
 */
public class Salida implements java.io.Serializable {

	private Integer idSalida;
	private Empleado empleado;
	private Producto producto;
	private Proyecto proyecto;
	private TipoTrabajo tipoTrabajo;
	private UnidadMedida unidadMedida;
	private String ordenTrabajo;
	private String modeloMueble;
	private Integer cantidad;
	private Date fecha;
	private Integer estatus;

	public Salida() {
	}

	public Salida(Producto producto, TipoTrabajo tipoTrabajo) {
		this.producto = producto;
		this.tipoTrabajo = tipoTrabajo;
	}

	public Salida(Empleado empleado, Producto producto, Proyecto proyecto, TipoTrabajo tipoTrabajo,
			UnidadMedida unidadMedida, String ordenTrabajo, String modeloMueble, Integer cantidad, Date fecha,
			Integer estatus) {
		this.empleado = empleado;
		this.producto = producto;
		this.proyecto = proyecto;
		this.tipoTrabajo = tipoTrabajo;
		this.unidadMedida = unidadMedida;
		this.ordenTrabajo = ordenTrabajo;
		this.modeloMueble = modeloMueble;
		this.cantidad = cantidad;
		this.fecha = fecha;
		this.estatus = estatus;
	}

	public Integer getIdSalida() {
		return this.idSalida;
	}

	public void setIdSalida(Integer idSalida) {
		this.idSalida = idSalida;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

	public TipoTrabajo getTipoTrabajo() {
		return this.tipoTrabajo;
	}

	public void setTipoTrabajo(TipoTrabajo tipoTrabajo) {
		this.tipoTrabajo = tipoTrabajo;
	}

	public UnidadMedida getUnidadMedida() {
		return this.unidadMedida;
	}

	public void setUnidadMedida(UnidadMedida unidadMedida) {
		this.unidadMedida = unidadMedida;
	}

	public String getOrdenTrabajo() {
		return this.ordenTrabajo;
	}

	public void setOrdenTrabajo(String ordenTrabajo) {
		this.ordenTrabajo = ordenTrabajo;
	}

	public String getModeloMueble() {
		return this.modeloMueble;
	}

	public void setModeloMueble(String modeloMueble) {
		this.modeloMueble = modeloMueble;
	}

	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

}
