package com.seidor.inventario.model;
// Generated 4 mar. 2024 12:06:49 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * TasaCuotaIva generated by hbm2java
 */
public class TasaCuotaIva implements java.io.Serializable {

	private Integer idTasaCuotaIva;
	private TipoMoneda tipoMoneda;
	private BigDecimal tasaCuotaIva;
	private String descripcion;
	private Boolean fdl;
	private Integer cbu;
	private Date cat;
	private Integer luu;
	private Date uat;

	public TasaCuotaIva() {
	}

	public TasaCuotaIva(TipoMoneda tipoMoneda, BigDecimal tasaCuotaIva, String descripcion, Boolean fdl, Integer cbu,
			Date cat, Integer luu, Date uat) {
		this.tipoMoneda = tipoMoneda;
		this.tasaCuotaIva = tasaCuotaIva;
		this.descripcion = descripcion;
		this.fdl = fdl;
		this.cbu = cbu;
		this.cat = cat;
		this.luu = luu;
		this.uat = uat;
	}

	public Integer getIdTasaCuotaIva() {
		return this.idTasaCuotaIva;
	}

	public void setIdTasaCuotaIva(Integer idTasaCuotaIva) {
		this.idTasaCuotaIva = idTasaCuotaIva;
	}

	public TipoMoneda getTipoMoneda() {
		return this.tipoMoneda;
	}

	public void setTipoMoneda(TipoMoneda tipoMoneda) {
		this.tipoMoneda = tipoMoneda;
	}

	public BigDecimal getTasaCuotaIva() {
		return this.tasaCuotaIva;
	}

	public void setTasaCuotaIva(BigDecimal tasaCuotaIva) {
		this.tasaCuotaIva = tasaCuotaIva;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Boolean getFdl() {
		return this.fdl;
	}

	public void setFdl(Boolean fdl) {
		this.fdl = fdl;
	}

	public Integer getCbu() {
		return this.cbu;
	}

	public void setCbu(Integer cbu) {
		this.cbu = cbu;
	}

	public Date getCat() {
		return this.cat;
	}

	public void setCat(Date cat) {
		this.cat = cat;
	}

	public Integer getLuu() {
		return this.luu;
	}

	public void setLuu(Integer luu) {
		this.luu = luu;
	}

	public Date getUat() {
		return this.uat;
	}

	public void setUat(Date uat) {
		this.uat = uat;
	}

}
