package com.seidor.inventario.model;
// Generated 4 mar. 2024 12:06:49 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TiposMovimiento generated by hbm2java
 */
public class TiposMovimiento implements java.io.Serializable {

	private Integer idTipoMovimiento;
	private String descripcion;
	private Boolean fdl;
	private Integer cbu;
	private Date cat;
	private Integer luu;
	private Date uat;
	private Set movimientoses = new HashSet(0);
	private Set folioses = new HashSet(0);

	public TiposMovimiento() {
	}

	public TiposMovimiento(String descripcion, Boolean fdl, Integer cbu, Date cat, Integer luu, Date uat,
			Set movimientoses, Set folioses) {
		this.descripcion = descripcion;
		this.fdl = fdl;
		this.cbu = cbu;
		this.cat = cat;
		this.luu = luu;
		this.uat = uat;
		this.movimientoses = movimientoses;
		this.folioses = folioses;
	}

	public Integer getIdTipoMovimiento() {
		return this.idTipoMovimiento;
	}

	public void setIdTipoMovimiento(Integer idTipoMovimiento) {
		this.idTipoMovimiento = idTipoMovimiento;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Boolean getFdl() {
		return this.fdl;
	}

	public void setFdl(Boolean fdl) {
		this.fdl = fdl;
	}

	public Integer getCbu() {
		return this.cbu;
	}

	public void setCbu(Integer cbu) {
		this.cbu = cbu;
	}

	public Date getCat() {
		return this.cat;
	}

	public void setCat(Date cat) {
		this.cat = cat;
	}

	public Integer getLuu() {
		return this.luu;
	}

	public void setLuu(Integer luu) {
		this.luu = luu;
	}

	public Date getUat() {
		return this.uat;
	}

	public void setUat(Date uat) {
		this.uat = uat;
	}

	public Set getMovimientoses() {
		return this.movimientoses;
	}

	public void setMovimientoses(Set movimientoses) {
		this.movimientoses = movimientoses;
	}

	public Set getFolioses() {
		return this.folioses;
	}

	public void setFolioses(Set folioses) {
		this.folioses = folioses;
	}

}
