package com.seidor.inventario.model;
// Generated 12 abr. 2024 12:10:56 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoMoneda generated by hbm2java
 */
public class TipoMoneda implements java.io.Serializable {

	private Integer idMoneda;
	private String moneda;
	private String descripcion;
	private Boolean fdl;
	private Integer cbu;
	private Date cat;
	private Integer luu;
	private Date uat;
	private Set detalleMovimientos = new HashSet(0);
	private Set tasaCuotaIvas = new HashSet(0);
	private Set detalleOrdenCompras = new HashSet(0);
	private Set ordenCompras = new HashSet(0);
	private Set proveedors = new HashSet(0);

	public TipoMoneda() {
	}

	public TipoMoneda(String moneda, String descripcion, Boolean fdl, Integer cbu, Date cat, Integer luu, Date uat,
			Set detalleMovimientos, Set tasaCuotaIvas, Set detalleOrdenCompras, Set ordenCompras, Set proveedors) {
		this.moneda = moneda;
		this.descripcion = descripcion;
		this.fdl = fdl;
		this.cbu = cbu;
		this.cat = cat;
		this.luu = luu;
		this.uat = uat;
		this.detalleMovimientos = detalleMovimientos;
		this.tasaCuotaIvas = tasaCuotaIvas;
		this.detalleOrdenCompras = detalleOrdenCompras;
		this.ordenCompras = ordenCompras;
		this.proveedors = proveedors;
	}

	public Integer getIdMoneda() {
		return this.idMoneda;
	}

	public void setIdMoneda(Integer idMoneda) {
		this.idMoneda = idMoneda;
	}

	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Boolean getFdl() {
		return this.fdl;
	}

	public void setFdl(Boolean fdl) {
		this.fdl = fdl;
	}

	public Integer getCbu() {
		return this.cbu;
	}

	public void setCbu(Integer cbu) {
		this.cbu = cbu;
	}

	public Date getCat() {
		return this.cat;
	}

	public void setCat(Date cat) {
		this.cat = cat;
	}

	public Integer getLuu() {
		return this.luu;
	}

	public void setLuu(Integer luu) {
		this.luu = luu;
	}

	public Date getUat() {
		return this.uat;
	}

	public void setUat(Date uat) {
		this.uat = uat;
	}

	public Set getDetalleMovimientos() {
		return this.detalleMovimientos;
	}

	public void setDetalleMovimientos(Set detalleMovimientos) {
		this.detalleMovimientos = detalleMovimientos;
	}

	public Set getTasaCuotaIvas() {
		return this.tasaCuotaIvas;
	}

	public void setTasaCuotaIvas(Set tasaCuotaIvas) {
		this.tasaCuotaIvas = tasaCuotaIvas;
	}

	public Set getDetalleOrdenCompras() {
		return this.detalleOrdenCompras;
	}

	public void setDetalleOrdenCompras(Set detalleOrdenCompras) {
		this.detalleOrdenCompras = detalleOrdenCompras;
	}

	public Set getOrdenCompras() {
		return this.ordenCompras;
	}

	public void setOrdenCompras(Set ordenCompras) {
		this.ordenCompras = ordenCompras;
	}

	public Set getProveedors() {
		return this.proveedors;
	}

	public void setProveedors(Set proveedors) {
		this.proveedors = proveedors;
	}

}
