package com.seidor.inventario.model;
// Generated 22 feb. 2023 19:54:18 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * UnidadMedida generated by hbm2java
 */
public class UnidadMedida implements java.io.Serializable {

	private Integer idUnidadMedida;
	private String unidadMedida;
	private String descripcion;
	private int activo;
	private Set entradas = new HashSet(0);
	private Set productos = new HashSet(0);
	private Set salidas = new HashSet(0);

	public UnidadMedida() {
	}

	public UnidadMedida(String unidadMedida, String descripcion, int activo) {
		this.unidadMedida = unidadMedida;
		this.descripcion = descripcion;
		this.activo = activo;
	}

	public UnidadMedida(String unidadMedida, String descripcion, int activo, Set entradas, Set productos, Set salidas) {
		this.unidadMedida = unidadMedida;
		this.descripcion = descripcion;
		this.activo = activo;
		this.entradas = entradas;
		this.productos = productos;
		this.salidas = salidas;
	}

	public Integer getIdUnidadMedida() {
		return this.idUnidadMedida;
	}

	public void setIdUnidadMedida(Integer idUnidadMedida) {
		this.idUnidadMedida = idUnidadMedida;
	}

	public String getUnidadMedida() {
		return this.unidadMedida;
	}

	public void setUnidadMedida(String unidadMedida) {
		this.unidadMedida = unidadMedida;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public int getActivo() {
		return this.activo;
	}

	public void setActivo(int activo) {
		this.activo = activo;
	}

	public Set getEntradas() {
		return this.entradas;
	}

	public void setEntradas(Set entradas) {
		this.entradas = entradas;
	}

	public Set getProductos() {
		return this.productos;
	}

	public void setProductos(Set productos) {
		this.productos = productos;
	}

	public Set getSalidas() {
		return this.salidas;
	}

	public void setSalidas(Set salidas) {
		this.salidas = salidas;
	}

}
